/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 globeee.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/globeee.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[-0.14, 0.02, -0.72]} rotation={[0, -0.76, 0]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.005']} position={[1.35, 0.03, -0.48]} rotation={[0, -0.83, 0]} scale={-0.04}>
        <mesh geometry={nodes.Text.geometry} material={materials['Material.006']} position={[6.34, -1.59, -6.81]} rotation={[1.55, 0.01, -0.83]} scale={-1.52} />
        <mesh geometry={nodes.Text001.geometry} material={materials['Material.006']} position={[2.9, -11.3, -39.95]} rotation={[1.45, -0.18, -2.39]} scale={-1.52} />
        <mesh geometry={nodes.Text002.geometry} material={materials['Material.006']} position={[20.69, -26.45, -27.38]} rotation={[1.49, -0.12, -2.27]} scale={-4.04} />
        <mesh geometry={nodes.Text003.geometry} material={materials['Material.006']} position={[42.41, -0.26, 8.35]} rotation={[1.64, -0.02, -2.39]} scale={-1.52} />
      </mesh>
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.005']} position={[0.02, 0.54, 0.67]} rotation={[0, -0.83, 0]} scale={-0.04} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.005']} position={[-0.45, 0.91, -1.4]} rotation={[0, -0.83, 0]} scale={-0.04} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.005']} position={[0.39, 0.07, -1.96]} rotation={[0, -0.83, 0]} scale={-0.04} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.005']} position={[-0.75, -1.07, -0.25]} rotation={[0, -0.83, 0]} scale={-0.04} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.005']} position={[-0.3, 0.78, 0.22]} rotation={[0, -0.83, 0]} scale={-0.04} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[1.13, 0.03, -0.48]} rotation={[0, 0, 1.57]} scale={[0.02, 0.23, 0.02]} />
    </group>
  )
}

useGLTF.preload('/globeee.gltf')
